# Examen

In [2]:
import numpy as np

## 2) Crear un vector de ceros de tamaño 10

In [3]:
arreglo_ceros = np.zeros(10)
arreglo_ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1

In [4]:
arreglo_ceros = np.zeros(10)
arreglo_ceros[5] = 1
arreglo_ceros

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [5]:
vector = np.arange(50)
vector = vector[::-1]
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [6]:
matriz = np.arange(9).reshape(3,3)
matriz

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 6) Encontrar los indices que no sean cero en un arreglo

In [7]:
arreglo = [1,2,0,0,4,0]
arreglo = np.array(arreglo)
mayor_cero = arreglo > 0
arreglo_sin_cero = arreglo[mayor_cero]
arreglo_sin_cero

array([1, 2, 4])

## 7) Crear una matriz de identidad 3 x 3

In [8]:
matriz_identidad = np.eye(3,3)
matriz_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [11]:
matriz_random = np.random.rand(3,3,3)
matriz_random

array([[[0.04917728, 0.45357574, 0.56946195],
        [0.52807986, 0.10797021, 0.41357167],
        [0.59865377, 0.08191252, 0.53831122]],

       [[0.82129056, 0.74006212, 0.92855172],
        [0.39161578, 0.39158749, 0.84359765],
        [0.5484218 , 0.01084193, 0.27385644]],

       [[0.2924268 , 0.97913794, 0.59974972],
        [0.59811408, 0.62108253, 0.18064443],
        [0.694959  , 0.31795271, 0.00395232]]])

## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [14]:
matriz_10_x_10 = np.arange(100).reshape(10,10) 
valor_minimo = matriz_10_x_10.min()
valor_maximo = matriz_10_x_10.max()
print(f"Valor minimo {valor_minimo}")
print(f"Valor maximo {valor_maximo}")

Valor minimo 0
Valor maximo 99


## 10) Sacar los colores RGB unicos en una imagen (cuales rgb existen ej: 0, 0, 0 - 255,255,255 -> 2 colores)

In [17]:
from scipy import misc

mapache = misc.face()
colores_rgb_unicos = np.unique(mapache.reshape(-1, mapache.shape[2]), axis=0)
colores_rgb_unicos[2]

array([0, 0, 9], dtype=uint8)

## 11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [18]:
import pandas as pd

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
serie = pd.Series(mydict)
serie

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [23]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
data_frame = ser.reset_index()
data_frame = pd.DataFrame(ser.index)
data_frame.columns = ['Valores']
data_frame

Valores
0        a
1        b
2        c
3        e
4        d
5        f
6        g
7        h
8        i
9        j
10       k
11       l
12       m
13       n
14       o
15       p
16       q
17       r
18       s
19       t
20       u
21       v
22       w
23       x
24       y
25       z

## 13) ¿Como combinar varias series para hacer un DataFrame?

In [30]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

data_frame_series = pd.DataFrame({'Letas': ser1,'Numeros': ser2})
data_frame_series

Letas  Numeros
0      a        0
1      b        1
2      c        2
3      e        3
4      d        4
5      f        5
6      g        6
7      h        7
8      i        8
9      j        9
10     k       10
11     l       11
12     m       12
13     n       13
14     o       14
15     p       15
16     q       16
17     r       17
18     s       18
19     t       19
20     u       20
21     v       21
22     w       22
23     x       23
24     y       24
25     z       25

## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [28]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

indices_serie1_no_serie_2 = ser1.isin(ser2)
valores_diferentes = ser1[np.invert(indices_serie1_no_serie_2)]
valores_diferentes

0    1
1    2
2    3
dtype: int64

## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?

In [35]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
indices_serie1_no_serie_2 = ser1.isin(ser2)
indices_serie2_no_serie_1 = ser2.isin(ser1)
valores_diferentes_serie_1 = ser1[np.invert(indices_serie1_no_serie_2)]
valores_diferentes_serie_2 = ser2[np.invert(indices_serie2_no_serie_1)]
valores_no_comunes = pd.concat([valores_diferentes_serie_1, valores_diferentes_serie_2])
valores_no_comunes

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [36]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
veces_repiten = ser.value_counts()
veces_repiten

h    6
f    5
c    5
e    4
a    3
b    3
g    2
d    2
dtype: int64

## 17) ¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?

In [44]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
valores_repetidos = ser.value_counts()
valores_repetidos.sort_values(ascending = False)
valores_repetidos[0:1] = 2
valores_repetidos[2:] = 0
valores_repetidos

4    2
2    3
3    0
1    0
dtype: int64

## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un shape definido?

## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?

In [45]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser.iloc[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?


In [55]:
ser1_1 = pd.Series(range(5))
ser2_2 = pd.Series(list('abcde'))
data_frame_horizontal = pd.DataFrame()
data_frame_horizontal = data_frame_vertical.append(ser1_1, ignore_index=True)
data_frame_horizontal = data_frame_vertical.append(ser2_2, ignore_index=True)
data_frame_horizontal


Letas Numeros    0    1    2    3    4
0    0.0       a  NaN  NaN  NaN  NaN  NaN
1    1.0       b  NaN  NaN  NaN  NaN  NaN
2    2.0       c  NaN  NaN  NaN  NaN  NaN
3    3.0       d  NaN  NaN  NaN  NaN  NaN
4    4.0       e  NaN  NaN  NaN  NaN  NaN
5    NaN     NaN    a    b    c    d    e

## 22)¿Como importar solo columnas especificas de un archivo csv?

In [58]:
path = 'BostonHousing.csv'
columnas = ['chas']
df = pd.read_csv(path, usecols=columnas)
df

chas
0       0
1       0
2       0
3       0
4       0
..    ...
501     0
502     0
503     0
504     0
505     0

[506 rows x 1 columns]