In [1]:
import numpy as np

In [4]:
arreglo_0_a_90_grados = np.array([0, 30, 45, 60, 90])
# arreglo_0_a_90_grados

array([ 0, 30, 45, 60, 90])

In [9]:
radianes = arreglo_0_a_90_grados * np.pi / 180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [10]:
# calcular el seno
seno =  np.sin(radianes)
seno

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [11]:
# calcular coseno
coseno = np.cos(radianes)
coseno 

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [13]:
# calcular tangente
tangente = np.tan(radianes)
tangente

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [18]:
# Funciones randomicas
arreglo_random = np.random.randint(10) # enteros positivos hasta el 10 - 1
arreglo_random #[0, 11[

2

In [21]:
# Arreglo con limites
random = np.random.randint(-2, 2) 
random #[-2, [2

0

In [23]:
# arreglo de randoms
arreglo_rdm = np.random.randint(0, 50, 4)
arreglo_rdm

array([ 6,  3,  4, 46])

In [24]:
# mean
arreglo_rdm.mean()

14.75

In [28]:
# mediana
np.median(arreglo_rdm)

5.0

In [29]:
# desviacion estandar
np.std(arreglo_rdm)

18.07449860992