In [1]:
import numpy as np

In [2]:
np.zeros((5, 7, 8))

np.ones((3, 5))

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
# generar numeros de 0 a 11
np.arange(12)
np.arange(12)
np.arange(4, 20) # intervalor [4, 20[
np.arange(-12, 1) # intervalo negativo
np.arange(0, 20, 2) # tercer parametro es de la diferencia de la secuencia
np.arange(-12, 1, 0.5)


array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ,   0.5])

In [4]:
arreglo_pares = np.arange(0, 20, 2)

arreglo_pares
print (arreglo_pares.size)
print (len(arreglo_pares))
arreglo_tres_dimensiones = np.zeros((2, 3, 4))
print (arreglo_tres_dimensiones.shape)

10
10
(2, 3, 4)


In [5]:
arreglo_pares.reshape(5, 2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [10]:
# arreglo de 24 elementos y todas las posibles combinaciones
np.arange(0, 24, 1)
np.arange(0, 24, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [11]:
a = np.array([10, 10, 10])
b = np.array([5, 5, 5])

In [12]:
# suma entre arreglos numpy
a + b

array([15, 15, 15])

In [13]:
# resta 
a - b

array([5, 5, 5])

In [14]:
# multiplicacion
a * b

array([50, 50, 50])

In [15]:
# division 
a / b

array([2., 2., 2.])

In [47]:
arr_3 = np.arange(-4, 16, 1).reshape(4, 5)
arr_4 = np.arange(0, 200, 10.5).reshape(4, 5)

In [48]:
arr_3

array([[-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [34]:
arr_4

array([[  0. ,  10.5,  21. ,  31.5,  42. ],
       [ 52.5,  63. ,  73.5,  84. ,  94.5],
       [105. , 115.5, 126. , 136.5, 147. ],
       [157.5, 168. , 178.5, 189. , 199.5]])

In [49]:
# suma
arr_3 + arr_4 

array([[ -4. ,   7.5,  19. ,  30.5,  42. ],
       [ 53.5,  65. ,  76.5,  88. ,  99.5],
       [111. , 122.5, 134. , 145.5, 157. ],
       [168.5, 180. , 191.5, 203. , 214.5]])

In [50]:
# resta
arr_3 - arr_4


array([[  -4. ,  -13.5,  -23. ,  -32.5,  -42. ],
       [ -51.5,  -61. ,  -70.5,  -80. ,  -89.5],
       [ -99. , -108.5, -118. , -127.5, -137. ],
       [-146.5, -156. , -165.5, -175. , -184.5]])

In [51]:
# modulo
a % b

array([0, 0, 0])

In [58]:
# Multiplicar
a * 10

# Sumar 
print (a+10)

# Resta 
print (a-0)

# Division 
print (a/10)

# No se puede igualar
# print (a = 19)

# Mod
print (a % 4)

[20 20 20]
[10 10 10]
[1. 1. 1.]
[2 2 2]


In [63]:
# Un arreglo y cuales son mayores que 5
arreglo_prueba = np.arange(20).reshape(5,2,2)
print (arreglo_prueba)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [64]:
mayores_cinco = arreglo_prueba > 5
print (mayores_cinco)

[[[False False]
  [False False]]

 [[False False]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


In [65]:
arreglo_prueba[mayores_cinco]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [130]:
mayor_6 = arreglo_prueba > 5
menor_12 = arreglo_prueba < 12
pares = arreglo_prueba % 2 == 0
respuesta = mayor_6  & menor_12 & pares

arreglo_prueba[respuesta]

array([ 6,  8, 10])

In [132]:
A = np.arange(4).reshape((2,2))
A

array([[0, 1],
       [2, 3]])

In [133]:
B = np.arange(4,8).reshape((2,2))
B

array([[4, 5],
       [6, 7]])

In [135]:
# Producto punto
np.dot(A, B)

array([[ 6,  7],
       [26, 31]])

In [136]:
np. dot(B, A)

array([[10, 19],
       [14, 27]])

In [152]:
arreglo_doce = np.arange(20)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [138]:
arreglo_doce.sum()

66

In [139]:
arreglo_doce.min()

0

In [140]:
arreglo_doce.max()

11

In [153]:
arreglo_doce.reshape(5,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [155]:
arreglo_doce.reshape(5,2,2).sum(axis=0)

array([[40, 45],
       [50, 55]])

In [156]:
arreglo_doce.reshape(5,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20],
       [26, 28],
       [34, 36]])

In [157]:
arreglo_doce.reshape(5,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21],
       [25, 29],
       [33, 37]])